### ISSUE TITLE
TO DO: Remove node_modules and add .gitignore

### ISSUE THREAD

**Issue by MelisaIm** [heggy231/kanbanBoard#3]
- Node modules are too heavy and will increase our development time by having to check in and check out so many files. Let's put them in a .gitignore and delete them from our git tracking.

**Comment by heggy231** [comment]
- Exclude `/node_modules`  from being tracked by git
1. Make sure not to add `/node_modules` folder before.  If so delete and `npm install` 
    Create .gitignore file
    >`**touch .gitignore**`
2. Inside of .gitIgnore file and add `**node_modules**` to ignore the `node_modules` directory
    > `**echo "node_modules" >> .gitignore**` 
// `echo` writes, `>>` indicates inside of what file 
// file starting with "." is hidden by default.  To see this file we need to add '-a' to display hidden file.

3. Expect to see no changes to commit since I configured .gitignore file to add `node_modules`
  > git status --ignored

// output:
On branch master
Your branch is up to date with 'origin/master'.

Changes not staged for commit:
  (use "git add/rm <file>..." to update what will be committed)
  (use "git checkout -- <file>..." to discard changes in working directory)

	modified:   node_modules/abab/package.json
	modified:   node_modules/accepts/package.json
	modified:   node_modules/acorn-dynamic-import/node_modules/acorn/package.json
	modified:   node_modules/acorn-dynamic-import/package.json
	modified:   node_modules/acorn-globals/node_modules/acorn/package.json
	modified:   node_modules/acorn-globals/package.json

// structure of my file
My file structure:
<git-root>
 - README.md
 - package.json
 - /public
 - /src
 - /node_modules

[reference code
](https://gist.github.com/paulallies/0052fab554b14bbfa3ef)
[referece config gitignore](https://youtu.be/N6wQ28h-MmE)

**Comment by MelisaIm** [comment]
Sounds good! 

Here's my process: 
1) Go to master; git checkout master
2) git pull to get my local master on par with origin master
3) Create and switch to a new branch to make the changes; git checkout -b delete_node_modules 
4) git rm -rf node_modules; commit -m "Deleted node_modules"
5) touch .gitignore
6) echo node_modules >> .gitignore
7) git add .gitignore; git commit -m "Added node_modules to .gitignore"
8) git push changes to branch delete_node_modules
9) Create a PR
10) Have you review the PR! 😁

**Comment by heggy231** [comment]
Will follow this instruction tomorrow morning!
